# Server configuration
server:
  port: 8080

spring:
  application:
    name: lost-and-found
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: <DB_USER_NAME>
    password: <DB_USER_PASSWORD>
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.Oracle12cDialect

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        orm: DEBUG
        transaction: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html